[package]
name = "spend"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
hex-literal = "0.4.1"
serde = "1.0.196"
serde_derive = "1.0.196"
serde_json = "1.0.113"
sha2 = "0.10.8"
